"""Development-only Phase 4B LOCAL DEMO data population.

Distinct from scripts/seed_phase4b.py (which stays untouched). This script:

1. Marks the EXISTING "Assam Down Town University" record as active +
   verified for local testing only (all other fields left intact).
2. Adds six additional realistic institutions designed to produce visibly
   different Phase 4B match scores (strong / medium / weak / excluded-
   unverified).
3. Optionally adds an education-domain demo challenge whose Problem DNA is
   generated by the REAL ProblemDnaService/classifier pipeline so the
   preserved Assam Down Town University profile can surface as a match.

Idempotent: safe to run repeatedly. Dev/local data only — never referenced
by migrations and never executed at application startup.

Usage (from backend/):
    .venv\\Scripts\\python.exe -m scripts.seed_local_demo
"""

from datetime import datetime, timezone

from sqlalchemy import func

from app.core.database import SessionLocal
from app.models.challenge import Challenge
from app.models.institution import (
    Institution,
    InstitutionStatus,
    InstitutionType,
    InstitutionVerificationStatus,
)
from app.models.institution_membership import (
    InstitutionMembershipRole,
    InstitutionMembershipStatus,
)
from app.repositories.membership_repository import MembershipRepository
from app.repositories.user_repository import UserRepository
from app.services.auth_service import pwd_context
from app.services.challenge_service import ChallengeService
from app.services.problem_dna_service import ProblemDnaService

ADTU_NAME = "Assam Down Town University"
ADTU_VERIFICATION_NOTE = (
    "DEV DEMO — manually verified for Phase 4B local testing"
)

ADDITIONAL_INSTITUTIONS = [
    # --- Strong matches ---------------------------------------------------
    {
        "name": "Deccan Water Resources Institute",
        "institution_type": InstitutionType.RESEARCH_INSTITUTE,
        "location": "Anantapur, Andhra Pradesh",
        "description": (
            "Research institute specialising in groundwater restoration, "
            "drinking water quality and drought resilience in Rayalaseema."
        ),
        "website": "https://dwri-example.org.in",
        "domains": ["water_sanitation", "agriculture", "environment"],
        "capabilities": {
            "expertise": [
                "Hydrology",
                "Groundwater recharge",
                "Water quality testing",
                "Drinking water treatment",
            ],
            "disciplines": ["Environmental Engineering", "Chemistry"],
            "research_areas": [
                "Borewell recharge structures",
                "Low-cost water purification",
            ],
            "technologies": ["IoT sensing", "Remote sensing", "GIS"],
            "facilities": ["Water Testing Lab", "Hydrogeology Field Station"],
            "project_experience": [
                "Village borewell rejuvenation program, Anantapur 2024",
                "Fluoride mitigation pilot in drinking water wells",
            ],
            "collaboration_modes": ["Field pilots", "Student projects"],
        },
        "verified": True,
    },
    {
        "name": "Kaveri Agricultural Sciences College",
        "institution_type": InstitutionType.COLLEGE,
        "location": "Mandya, Karnataka",
        "description": (
            "Agricultural college working directly with farmer producer "
            "organisations on market access and crop economics."
        ),
        "website": "https://kaveri-agri-example.edu.in",
        "domains": ["agriculture", "rural_livelihoods"],
        "capabilities": {
            "expertise": ["Agronomy", "Agricultural economics", "Market linkages"],
            "disciplines": ["Agricultural Engineering", "Rural Development"],
            "research_areas": ["Mandi price information systems"],
            "technologies": ["Mobile applications", "Data analytics"],
            "facilities": ["Agri Business Incubation Centre"],
            "project_experience": [
                "Farmer price-alert SMS service with FPOs, Mandya 2023"
            ],
        },
        "verified": True,
    },
    {
        "name": "GreenWaste Environmental Research Organisation",
        "institution_type": InstitutionType.RESEARCH_INSTITUTE,
        "location": "Bengaluru, Karnataka",
        "description": (
            "Applied research organisation for municipal solid waste "
            "segregation, composting and recycling supply chains."
        ),
        "domains": ["waste_management", "environment"],
        "capabilities": {
            "expertise": [
                "Solid waste management",
                "Composting",
                "Recycling supply chains",
            ],
            "research_areas": ["Waste segregation automation"],
            "technologies": ["IoT bin sensors", "Material recovery"],
            "facilities": ["Materials Recovery Testing Lab"],
            "project_experience": [
                "Ward-level segregation pilot with Bengaluru residents groups"
            ],
        },
        "verified": True,
    },
    # --- Medium matches -----------------------------------------------------
    {
        "name": "Hill State University of Technology",
        "institution_type": InstitutionType.UNIVERSITY,
        "location": "Shimla, Himachal Pradesh",
        "description": (
            "State university with electrical engineering and mountain "
            "infrastructure programs."
        ),
        "domains": ["energy", "infrastructure"],
        "capabilities": {
            "expertise": ["Renewable energy", "Electrical Engineering"],
            "research_areas": ["Solar micro-grids for remote villages"],
            "technologies": ["Solar", "Smart metering"],
            "facilities": ["Power Systems Lab"],
        },
        "verified": True,
    },
    # --- Weak / different-domain eligible match -----------------------------
    {
        "name": "Bayview Institute of Digital Studies",
        "institution_type": InstitutionType.COLLEGE,
        "location": "Visakhapatnam, Andhra Pradesh",
        "description": (
            "Computing-focused college; included in the demo set as a "
            "deliberately weak cross-domain candidate."
        ),
        "domains": ["digital_services", "education"],
        "capabilities": {
            "expertise": ["Web development", "Networking"],
            "facilities": ["Computer Center"],
        },
        "verified": True,
    },
    # --- Unverified but otherwise strong-looking (must be excluded) ---------
    {
        "name": "Ganga Rejuvenation Research Centre",
        "institution_type": InstitutionType.RESEARCH_INSTITUTE,
        "location": "Varanasi, Uttar Pradesh",
        "description": (
            "UNVERIFIED ON PURPOSE: capability profile deliberately looks "
            "like a top water-sector match to prove Phase 4B excludes "
            "unverified institutions purely on trust status."
        ),
        "domains": ["water_sanitation", "agriculture"],
        "capabilities": {
            "expertise": [
                "Hydrology",
                "River ecology",
                "Drinking water treatment",
                "Water quality monitoring",
            ],
            "research_areas": ["Low-cost water purification"],
            "technologies": ["IoT sensing"],
            "facilities": ["Water Testing Lab"],
            "project_experience": ["Riverside town drinking water study"],
        },
        "verified": False,
    },
]

# Education/Guwahati challenge so the PRESERVED Assam Down Town University
# profile (education + healthcare, AI/infrastructure research, Guwahati)
# legitimately appears in recommendations. DNA comes from the real pipeline.
EXTRA_CHALLENGE = {
    "title": "Village schools near Guwahati lack digital learning support",
    "description": (
        "Students in government schools around Guwahati share almost no "
        "computers, and teachers have no training for digital learning. "
        "Basic computer literacy and simple e-learning content would keep "
        "children from falling behind."
    ),
    "location": "Guwahati, Assam",
}

# --- Demo users and memberships for Phase 4C local testing ---------------
DEMO_USERS = [
    {
        "email": "reviewer@aikyra.dev",
        "password": "reviewer123",
        "full_name": "Demo Platform Reviewer",
        "is_platform_reviewer": True,
    },
    {
        "email": "owner@adtu.dev",
        "password": "owner123",
        "full_name": "ADTU Demo Owner",
        "is_platform_reviewer": False,
    },
    {
        "email": "student@adtu.dev",
        "password": "student123",
        "full_name": "ADTU Demo Student",
        "is_platform_reviewer": False,
    },
]

DEMO_MEMBERSHIPS = [
    {
        "email": "owner@adtu.dev",
        "role": InstitutionMembershipRole.OWNER,
    },
    # student@adtu.dev is a STUDENT member so team leads can invite them to a
    # team — the invite endpoint only accepts users who already hold an ACTIVE
    # faculty/student membership at the team's institution, and no API exists
    # to grant memberships (they are seeded data only).
    {
        "email": "student@adtu.dev",
        "role": InstitutionMembershipRole.STUDENT,
    },
    # Note: reviewer@aikyra.dev is a PLATFORM reviewer, not an institution member.
    # Platform reviewers verify institutions across the platform without
    # needing institution-specific memberships.
]


class _Payload:
    """Minimal stand-in for the create schema used by
    ChallengeService.create_challenge(model_dump())."""

    def __init__(self, data: dict) -> None:
        self._data = data

    def model_dump(self) -> dict:
        return dict(self._data)


def main() -> None:
    db = SessionLocal()
    try:
        # --- 1. Verify the EXISTING Assam Down Town University record ------
        adtu = db.query(Institution).filter(Institution.name == ADTU_NAME).first()
        if adtu is None:
            raise SystemExit(
                f"ERROR: expected existing institution '{ADTU_NAME}' not found; "
                "refusing to create it implicitly."
            )
        changed = False
        if adtu.status != InstitutionStatus.ACTIVE:
            adtu.status = InstitutionStatus.ACTIVE
            changed = True
        if adtu.verification_status != InstitutionVerificationStatus.VERIFIED:
            adtu.verification_status = InstitutionVerificationStatus.VERIFIED
            adtu.verification_note = ADTU_VERIFICATION_NOTE
            adtu.verified_at = datetime.now(timezone.utc)
            # verified_by intentionally left NULL — no fake user IDs.
            changed = True
        elif adtu.verification_note != ADTU_VERIFICATION_NOTE:
            adtu.verification_note = ADTU_VERIFICATION_NOTE
            changed = True
        db.commit()
        print(f"[adtu] {adtu.name}: active + verified ({'updated' if changed else 'already set'})")

        # --- 2. Additional institutions ------------------------------------
        created = skipped = 0
        for spec in ADDITIONAL_INSTITUTIONS:
            spec = dict(spec)
            verified = spec.pop("verified")
            exists = db.query(Institution).filter(Institution.name == spec["name"]).first()
            if exists:
                skipped += 1
                continue
            db.add(
                Institution(
                    **spec,
                    status=InstitutionStatus.ACTIVE,
                    verification_status=(
                        InstitutionVerificationStatus.VERIFIED
                        if verified
                        else InstitutionVerificationStatus.UNVERIFIED
                    ),
                    verification_note=(
                        None if verified else "DEV DEMO — left unverified to test exclusion"
                    ),
                )
            )
            created += 1
        db.commit()
        print(f"[institutions] {created} created, {skipped} already present")

        # --- 3. Extra demo challenge via the REAL DNA pipeline --------------
        challenge_service = ChallengeService(db)
        dna_service = ProblemDnaService(db)
        exists = (
            db.query(Challenge)
            .filter(Challenge.title == EXTRA_CHALLENGE["title"])
            .first()
        )
        if exists:
            print("[challenge] already present — DNA untouched")
        else:
            challenge = challenge_service.create_challenge(_Payload(EXTRA_CHALLENGE))
            dna, _ = dna_service.analyze_challenge(challenge.id)
            print(
                f"[challenge] created: {challenge.title[:60]} "
                f"[{dna.primary_domain} / conf={dna.confidence_score}]"
            )

        # --- 4. Demo users and memberships (Phase 4C) -----------------------
        def _ensure_user(db, email: str, password: str, full_name: str, is_platform_reviewer: bool = False):
            repo = UserRepository(db)
            user = repo.get_by_email(email)
            if user is not None:
                if user.is_platform_reviewer != is_platform_reviewer:
                    user.is_platform_reviewer = is_platform_reviewer
                    db.flush()
                return user, False
            user = repo.create(
                {
                    "email": email.lower(),
                    "hashed_password": pwd_context.hash(password),
                    "full_name": full_name,
                    "is_platform_reviewer": is_platform_reviewer,
                }
            )
            return user, True

        def _ensure_membership(db, user, institution, role):
            repo = MembershipRepository(db)
            membership = repo.get_membership(user.id, institution.id)
            if membership is not None:
                return membership, False
            membership = repo.create(
                {
                    "user_id": user.id,
                    "institution_id": institution.id,
                    "role": role,
                    "status": InstitutionMembershipStatus.ACTIVE,
                }
            )
            return membership, True

        users_created = users_reused = 0
        user_map = {}
        for spec in DEMO_USERS:
            user, created = _ensure_user(
                db, spec["email"], spec["password"], spec["full_name"],
                spec.get("is_platform_reviewer", False)
            )
            user_map[spec["email"]] = user
            if created:
                users_created += 1
            else:
                users_reused += 1
        db.commit()

        memberships_created = memberships_reused = 0
        for spec in DEMO_MEMBERSHIPS:
            user = user_map[spec["email"]]
            _, created = _ensure_membership(db, user, adtu, spec["role"])
            if created:
                memberships_created += 1
            else:
                memberships_reused += 1
        db.commit()

        print(
            f"[users] {users_created} created, {users_reused} already present"
        )
        print(
            f"[memberships] {memberships_created} created, "
            f"{memberships_reused} already present"
        )

        # Print the student's user UUID — the team-invite API references users
        # by user_id only (no person search exists yet), so reviewers need it
        # to run the invite → accept journey.
        student = user_map.get("student@adtu.dev")
        if student is None:
            repo = UserRepository(db)
            student = repo.get_by_email("student@adtu.dev")
        if student is not None:
            print(f"[invite] student user id (use in team invite): {student.id}")
    finally:
        db.close()


if __name__ == "__main__":
    main()
