"""create problem_dna table

Revision ID: 4140091755aa
Revises: 6f895f205e06
Create Date: 2026-08-26 00:27:41.797264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4140091755aa'
down_revision: Union[str, None] = '6f895f205e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_dna',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('primary_domain', sa.String(length=50), nullable=True),
    sa.Column('secondary_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('problem_type', sa.String(length=100), nullable=True),
    sa.Column('geographic_context', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', 'critical', name='urgency_level'), server_default='medium', nullable=False),
    sa.Column('affected_stakeholders', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_expertise', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('potential_solution_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by', sa.Enum('deterministic_baseline', 'ai_model', 'human', name='dna_source'), server_default='deterministic_baseline', nullable=False),
    sa.Column('analyzer_version', sa.String(length=50), nullable=False),
    sa.Column('validation_status', sa.Enum('pending_validation', 'validated', 'needs_review', name='dna_validation_status'), server_default='pending_validation', nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_dna')
    # drop_table does not remove PostgreSQL enum types automatically.
    for enum_name in ('urgency_level', 'dna_source', 'dna_validation_status'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
