"""add created_at index on challenges

Revision ID: 6f895f205e06
Revises: dbefd1316b42
Create Date: 2026-08-25 22:38:38.177695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f895f205e06'
down_revision: Union[str, None] = 'dbefd1316b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_challenges_created_at', 'challenges', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_challenges_created_at', table_name='challenges')
    # ### end Alembic commands ###
