"""create challenges table

Revision ID: dbefd1316b42
Revises: 
Create Date: 2026-08-25 22:19:17.291317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbefd1316b42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'validated', 'rejected', name='challenge_status'), server_default='submitted', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_challenges_status', 'challenges', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_challenges_status', table_name='challenges')
    op.drop_table('challenges')
    # drop_table does not remove the PostgreSQL enum type automatically.
    sa.Enum(
        'submitted', 'under_review', 'validated', 'rejected', name='challenge_status'
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
